version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: healthtracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=healthtracker
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
